### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by VantorreWannes** [VantorreWannes/ContentWarnings#1]
Write a fitting `README.md` for the project.

## Todo:
- [x] Use a readme generator.
- [x] Include a short summary of what out project is about and how it works.
- [x] Include a showcase section outlining the features of our project.
- [x] Include a section outlining all the enabled features in our GitHub repo.
- [x] Add a placeholder `contributing.md` file.

## Definition Of Done:
- [x] Did you create a new branch?
- [x] Did you commit after each major change?
- [x] Did you complete all steps outlined in this issue?
- [x] Did you make a pull request to merge with the dev branch?
