### ISSUE TITLE
Add more content categories

### ISSUE THREAD

**Issue by VantorreWannes** [VantorreWannes/ContentWarnings#10]
Add more detectable content categories and associated flag phrases.

## Todo

- [x] Generate flag phrases associated with certain content categories.
- [x] Run `format.py` to correctly link the flag phrases to their content categories. 
- [x] Test extension functionality with each content category addition.

## Definition Of Done

- [x] Did you create a new branch?
- [x] Did you commit after each major change?
- [x] Did you complete all steps outlined in this issue?
- [x] Did you make a pull request to merge with the dev branch?
