### ISSUE TITLE
Add content category picker

### ISSUE THREAD

**Issue by VantorreWannes** [VantorreWannes/ContentWarnings#12]
Add a way to select which content categories to warn for.

## Todo

- [x] #14
- [ ] Add a `active_content_categories.json` file.
- [ ] Add a way for the user to change the content of `active_content_categories.json`.
- [ ] Show only triggered content categories that are in `active_content_categories.json`. But still look for others in order to support statistics. 

## Definition Of Done

- [ ] Did you create a new branch?
- [ ] Did you commit after each major change?
- [ ] Did you complete all steps outlined in this issue?
- [ ] Did you make a pull request to merge with the dev branch?
