### ISSUE TITLE
Re-organize project layout. 

### ISSUE THREAD

**Issue by VantorreWannes** [VantorreWannes/ContentWarnings#14]
Re-organize project layout. Formalize into an actual web extension. 

## Todo

- [x] Formalize the layout of the project to be structurally sound.
- [x] Migrate project to typescript.
- [x] Refactor code to be structured well.

## Definition Of Done

- [x] Did you create a new branch?
- [x] Did you commit after each major change?
- [x] Did you complete all steps outlined in this issue?
- [x] Did you make a pull request to merge with the dev branch?
