### ISSUE TITLE
[Feature]: Implement interactive extension window

### ISSUE THREAD

**Issue by VantorreWannes** [VantorreWannes/ContentWarnings#18]
### Description

Implement an interactive extension window

### Todo

- [ ] Create HTML window layout in `menu.html`.
- [ ] Style `menu.html` with CSS.
- [ ] Adjust `manifest.json` to include and link the new `menu.html` file.
- [ ] Dynamically show content warnings for each page in `menu.html`.

### Definition Of Done

- [ ] Did you create a new branch?
- [ ]  Did you commit after each major change?
- [ ] Did you complete all steps outlined in this issue?
- [ ]  Did you make a pull request to merge with the dev branch?
