### ISSUE TITLE
Create issue templates

### ISSUE THREAD

**Issue by VantorreWannes** [VantorreWannes/ContentWarnings#3]
Decide and create GitHub issue templates.

## Todo:
- [x] Decide a general GitHub issue layout.
- [x] Create a `Definition Of Done` template.
- [x] Create GitHub Issue templates for this project. 

## Definition Of Done:
- [x] Did you create a new branch?
- [x] Did you commit after each major change?
- [x] Did you complete all steps outlined in this issue?
- [x] Did you make a pull request to merge with the dev branch?
