### ISSUE TITLE
Generate mockup data

### ISSUE THREAD

**Issue by VantorreWannes** [VantorreWannes/ContentWarnings#5]
Generate JSON mockup categories and words. 

## Todo:
- [x] Create a temporary markdown format to store each ChatGPT response into.
- [x] Generate a list of categories
- [x] Generate lists of associated words for each category.
- [x] Link together the words and categories in an improved format.

## Definition Of Done:
- [x] Did you create a new branch?
- [x] Did you commit after each major change?
- [x] Did you complete all steps outlined in this issue?
- [x] Did you make a pull request to merge with the dev branch?
