### ISSUE TITLE
Implement prototype functionality

### ISSUE THREAD

**Issue by VantorreWannes** [VantorreWannes/ContentWarnings#8]
Implement the prototype's core functionality.

## Todo 

- [x] Implement `data.json` parsing to JS object.
- [x] Implement setting parsed `data.json` content to Firefox `localStorage`.
- [x] Implement flag phrases detection using a dict/hasmap.
- [x] Log most likely content categories to be found on this page to console. 

## Definition Of Done

- [x] Did you create a new branch?
- [x] Did you commit after each major change?
- [x] Did you complete all steps outlined in this issue?
- [ ] Did you make a pull request to merge with the dev branch?
